### ISSUE TITLE
Clone object version 0.37 does not match bootstrap parameter 0.38

### ISSUE THREAD

**Issue by 0xaf1f** [liyuxin-bioinformatics/JUMPg#2]
While testing the example with the latest version from this repository, I get the following error:
```
-------------------------------------------------------------------------------------
Performing PSM filtering
-------------------------------------------------------------------------------------
Clone object version 0.37 does not match bootstrap parameter 0.38 at /usr/local/Perl/5.18.2/lib/perl5/5.18.2/x86_64-linux-thread-multi-ld/DynaLoader.pm line 213.
Compilation failed in require at /usr/local/apps/jumpg/2.3.5/programs/f/jump_f.pl line 23.
BEGIN failed--compilation aborted at /usr/local/apps/jumpg/2.3.5/programs/f/jump_f.pl line 23.
```

My perl installation already has Clone.pm (0.37) as `/usr/local/perl/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi-ld/Clone.pm`. Adding `/usr/local/apps/jumpg/2.3.5/programs/f` to `LD_LIBRARY_PATH` or `PERL5LIB` didn't work. Your bundled version is not completely overriding my installed version, but I'm not sure how to fix that. Is the bundled version necessary?

**Comment by liyuxin-bioinformatics** [comment]
Thanks for the report!

I have just uploaded our latest version (v2.3.6), in which the bundled Clone.pm has been removed. Could you please try and let me know how it works in your machine?

**Comment by 0xaf1f** [comment]
I'm sorry for the delay. That is working now, but I ran into a different problem later on, for which I'll file a new issue. For this, I was mostly wondering if the bundled version was special and needed to be used, so I guess the answer to that is no. :)

**Comment by 0xaf1f** [comment]
>  I ran into a different problem later on, for which I'll file a new issue.

I was getting an error with the program trying to access /var/ww for some reason, but I also had an incorrect path to the proteome reference file which was causing trouble before that. I didn't get the html error after fixing the proteome reference path and rerunning.
